### ISSUE TITLE
Missing spring-cloud-starter-stream-sink-cassandra update in Einstein.M1 Pre-release of Spring Cloud Stream App Starters

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/cassandra#10]
_From @dk0de on December 28, 2018 3:38_

Is it unmaintained since verion 1.3.1.RELEASE?
https://github.com/spring-cloud-stream-app-starters/app-starters-release/releases/tag/vEinstein.M1

Is a release planned soon?

https://stackoverflow.com/q/53953363

_Copied from original issue: spring-cloud-stream-app-starters/app-starters-release#171_

**Comment by sabbyanandan** [comment]
Hi, @dk0de. We have prepared for the 2.0 release but at the time of Darwin/2.0 release-train release, the dependent artifacts weren't ready for primetime, so the app didn't make it on the train. We will revisit it for the Einstein release-train release. Thank you for bringing it up.

**Comment by sabbyanandan** [comment]
Hi, @artembilan. When you get a chance, could you guide us whether if there's anything we need from SI-Extensions or any other dependency, so this App can be Boot 2.1 compatible?

**Comment by artembilan** [comment]
Yeah... The point is that we need to update and redo Spring Integration Cassandra extension first of all: https://github.com/spring-projects/spring-integration-extensions/issues/199
And only after that we are good to fix this sink and include it into the next release train.

**Comment by artembilan** [comment]
This is how Spring Integration Cassandra has been fixed: https://github.com/spring-projects/spring-integration-extensions/commit/6a9af8fc8ab47cba19cbce3da95849e2eed250b3

So, I think we are good to proceed with this App Starter now.
I'm not going to release that one yet, since the work what is done here might be as a feedback for some fixes and improvements over there.
